// Functional audiobooks with real audio files generated by edge-tts
const FUNCTIONAL_AUDIOBOOKS = [
  {
    id: "aab-001",
    title: "Messages from the Angels of Prosperity",
    subtitle: "Inspirational angel-themed reflections for hope, abundance, courage and renewal",
    language: "en",
    category: "spirituality",
    availability: "audio-ready",
    price: 9.99,
    currency: "USD",
    chapters: [
      {
        number: 1,
        title: "Introduction to Angelic Guidance",
        file: "audiobooks/messages_from_the_angels_of_prosperity/001_Introduction_to_Angelic_Guidance.mp3",
        duration: 45
      },
      {
        number: 2,
        title: "The Angel of Hope",
        file: "audiobooks/messages_from_the_angels_of_prosperity/002_The_Angel_of_Hope.mp3",
        duration: 52
      },
      {
        number: 3,
        title: "The Angel of Abundance",
        file: "audiobooks/messages_from_the_angels_of_prosperity/003_The_Angel_of_Abundance.mp3",
        duration: 48
      },
      {
        number: 4,
        title: "The Angel of Courage",
        file: "audiobooks/messages_from_the_angels_of_prosperity/004_The_Angel_of_Courage.mp3",
        duration: 50
      },
      {
        number: 5,
        title: "The Angel of Renewal",
        file: "audiobooks/messages_from_the_angels_of_prosperity/005_The_Angel_of_Renewal.mp3",
        duration: 47
      }
    ],
    cover: "assets/covers/aab-001.png",
    totalDuration: 242, // ~4 minutes
    wordCount: 850,
    narrator: "Jenny (Microsoft Edge TTS)",
    releaseDate: "2026-06-07"
  },
  {
    id: "aab-002",
    title: "Mensajes de los Ángeles de la Prosperidad",
    subtitle: "Reflexiones angélicas inspiradoras para esperanza, abundancia, coraje y renovación",
    language: "es",
    category: "spirituality",
    availability: "audio-ready",
    price: 9.99,
    currency: "USD",
    chapters: [
      {
        number: 1,
        title: "Introducción a la Guía Angélica",
        file: "audiobooks/mensajes_de_los_angeles_de_la_prosperidad/001_Introducción_a_la_Guía_Angélica.mp3",
        duration: 42
      },
      {
        number: 2,
        title: "El Ángel de la Esperanza",
        file: "audiobooks/mensajes_de_los_angeles_de_la_prosperidad/002_El_Ángel_de_la_Esperanza.mp3",
        duration: 50
      },
      {
        number: 3,
        title: "El Ángel de la Abundancia",
        file: "audiobooks/mensajes_de_los_angeles_de_la_prosperidad/003_El_Ángel_de_la_Abundancia.mp3",
        duration: 48
      },
      {
        number: 4,
        title: "El Ángel del Coraje",
        file: "audiobooks/mensajes_de_los_angeles_de_la_prosperidad/004_El_Ángel_del_Coraje.mp3",
        duration: 49
      },
      {
        number: 5,
        title: "El Ángel de la Renovación",
        file: "audiobooks/mensajes_de_los_angeles_de_la_prosperidad/005_El_Ángel_de_la_Renovación.mp3",
        duration: 51
      }
    ],
    cover: "assets/covers/aab-002.png",
    totalDuration: 240, // ~4 minutes
    wordCount: 820,
    narrator: "Elvira (Microsoft Edge TTS)",
    releaseDate: "2026-06-07"
  },
  {
    id: "aab-003",
    title: "The Thousand Sweet Recipes Treasury",
    subtitle: "Comprehensive guide to creating delicious desserts from around the world",
    language: "en",
    category: "recipes",
    availability: "audio-ready",
    price: 14.99,
    currency: "USD",
    chapters: [
      {
        number: 1,
        title: "Welcome to the Sweet Recipes Treasury",
        file: "audiobooks/the_thousand_sweet_recipes_treasury/001_Welcome_to_the_Sweet_Recipes_Treasury.mp3",
        duration: 38
      },
      {
        number: 2,
        title: "Essential Baking Tips",
        file: "audiobooks/the_thousand_sweet_recipes_treasury/002_Essential_Baking_Tips.mp3",
        duration: 42
      },
      {
        number: 3,
        title: "Classic Chocolate Chip Cookies",
        file: "audiobooks/the_thousand_sweet_recipes_treasury/003_Classic_Chocolate_Chip_Cookies.mp3",
        duration: 45
      }
    ],
    cover: "assets/covers/aab-003.png",
    totalDuration: 125, // ~2 minutes
    wordCount: 420,
    narrator: "Guy (Microsoft Edge TTS)",
    releaseDate: "2026-06-07"
  }
];

// Function to get functional audiobooks by language
function getFunctionalAudiobooks(language = 'en') {
  return FUNCTIONAL_AUDIOBOOKS.filter(book => book.language === language);
}

// Function to get audiobook by ID
function getFunctionalAudiobookById(id) {
  return FUNCTIONAL_AUDIOBOOKS.find(book => book.id === id);
}

// Function to get all functional audiobooks
function getAllFunctionalAudiobooks() {
  return FUNCTIONAL_AUDIOBOOKS;
}

// Function to format duration
function formatDuration(seconds) {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return `${mins}:${secs.toString().padStart(2, '0')}`;
}

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    FUNCTIONAL_AUDIOBOOKS,
    getFunctionalAudiobooks,
    getFunctionalAudiobookById,
    getAllFunctionalAudiobooks,
    formatDuration
  };
}
